### ISSUE TITLE
Handle missing values in the preview

### ISSUE THREAD

**Issue by petrpyszko** [Kentico/cloud-sample-app-react#115] opened 2018-10-23 11:21 UTC
### Motivation
The app crashes unexpectedly in the preview mode for articles without the image or products without the price. Preview Delivery API returns items in the draft step and some values can be missing (even required fields).

### Proposed solution
- The app should handle missing values and display some placeholder without data or with some explanation (e.g,. "Price TBA")
- check other possible occurences of this problem

### Additional context
![image](https://user-images.githubusercontent.com/16837895/47357197-5acc3080-d6c6-11e8-8b90-8a9d52c0a907.png)
- you can find some inspiration in the[ .NET sample app](https://github.com/Kentico/cloud-sample-app-net)
- related [cloud-sample-app-vue issue](https://github.com/Kentico/cloud-sample-app-vue/issues/18)

**Comment by pavan-krishna-v** [comment] 2018-10-23 14:50
@petrsvihlik  .. I see this is a new issue. Can i take it up. Or if you have already existing priority issues do let me know ! Thanks :)

**Comment by petrsvihlik** [comment] 2018-10-24 08:32
Hi @pavan-krishna-v, you can certainly pick it up! I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by pavan-krishna-v** [comment] 2018-10-24 13:30
> Hi @pavan-krishna-v, you can certainly pick it up! I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

Done. Thanks !

**Comment by pavan-krishna-v** [comment] 2018-10-29 13:16
> ### Motivation
> The app crashes unexpectedly in the preview mode for articles without the image or products without the price. Preview Delivery API returns items in the draft step and some values can be missing (even required fields).
> 
> ### Proposed solution
> * The app should handle missing values and display some placeholder without data or with some explanation (e.g,. "Price TBA")
> * check other possible occurences of this problem
> 
> ### Additional context
> ![image](https://user-images.githubusercontent.com/16837895/47357197-5acc3080-d6c6-11e8-8b90-8a9d52c0a907.png)
> 
> * you can find some inspiration in the[ .NET sample app](https://github.com/Kentico/cloud-sample-app-net)
> * related [cloud-sample-app-vue issue](https://github.com/Kentico/cloud-sample-app-vue/issues/18)


Hi @petrpyszko ,

    I understand that the issue is beyond just unavailablity of price. Also, i see that both coffee products are failing to load and both brewery pages are working. All the products have the price.
 The url which i checked is, http://localhost:3000/en-us/store/brewers.

  And i notice that all article pages are failing on clicking of preview. 

 Do let me know if i got the issue right.

**Comment by petrpyszko** [comment] 2018-11-01 14:50
Hi @pavan-krishna-v ,

yes, you are right, the App should be working even for the new (completely blank) items (brewers, articles ....). I am not sure which other fields can cause similar issues - but after creating blank items of each content type, you should be able to quickly identify other problematic areas :)

**Comment by Simply007** [comment] 2018-12-06 11:44
Hi @pavan-krishna-v,

since this is a sample application, it is completely fine to have just a show case, how to implement missing values. So it will be OK to protect only articles or products and not to implement all the cases where we could face missing values.

Take a look to the solution in our [Vue sample app](https://github.com/Kentico/cloud-sample-app-vue/pull/19) for inspiration.

Hope it helps 😄

**Comment by Simply007** [comment] 2019-01-16 07:35
Hello @pavan-krishna-v ,

do you have any update on this issue?

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-01-27 01:45
If efforts to solve this issue has been abandoned, I'd like to take it. However, I don't see the issue for this page. Please provide information on how to reproduce error.

**Comment by petrsvihlik** [comment] 2019-01-27 16:42
Hi @Karl-EdwardFPJeanMehu , I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

You should be able to reproduce the issue if you turn on the preview functionality as described at https://github.com/Kentico/cloud-sample-app-react#previewing-content-from-your-project

You can generate a sample project at https://app.kenticocloud.com/sample-project-generator and turn on the preview functionality as described at https://developer.kenticocloud.com/docs/previewing-content-in-a-separate-environment#section-using-the-delivery-preview-api

**Comment by Simply007** [comment] 2019-01-28 07:19
Hi @Karl-EdwardFPJeanMehu,

in the related task (basically the same but in Vue application),  [there is a description](https://github.com/Kentico/cloud-sample-app-vue/pull/19#issuecomment-435821693) how to reproduce the error step by step).

But instead of `npm run serve`, you would use `npm start` and connection to the client is described here:
* https://github.com/Kentico/cloud-sample-app-react#connecting-to-your-sample-project

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-01-28 11:04
Thanks @Simply007 ! I'll check it out

**Comment by Simply007** [comment] 2019-01-28 11:20
If you have any question, feel free to ask!

If you want to assign this issue to you, just accept the invitation @petrsvihlik has sent you:
https://github.com/Kentico/cloud-sample-app-react/invitations

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-01-28 14:02
Invitation accepted. I was not able to reproduce the error. In fact I've got an other but somewhat similar error.

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-01-31 01:32
I had found the issue but just took some time to make sure. The metaData state variable is initially undefined. That is causing the typeError in the MetaData comp for all given prop values (ie metadataMetaTitle).

**Comment by Simply007** [comment] 2019-01-31 07:32
You mean [this occurrence of metaData](https://github.com/Kentico/cloud-sample-app-react/blob/86cc1e5a500de8282ef69bf04b6cc4fd0247e735/src/Stores/Home.js#L15)?

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-02-02 14:30
Thanks!

**Comment by Simply007** [comment] 2019-02-04 07:53
In a Vue.js there is [an image omited](https://github.com/Kentico/cloud-sample-app-vue/pull/19/files#diff-48bf359bb9d62bda17a5805ab100d8d1). 

I would be more for the placeholder div with the text: `<contenttype> has not <element name>` with the same size as the image to not corupt the layout.

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-02-04 20:56
Ok, I see it.

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-02-09 04:39
Nearly complete. Please advise for meta OG images. These can only be replaced by a default image.

**Comment by Simply007** [comment] 2019-02-11 08:31
I assume you mean the OG image that is passed to the [Metadata](https://github.com/Kentico/cloud-sample-app-react/blob/master/src/Components/Metadata.js#L23) component.
It is fine like it is implemented right now -  when you pass the `null` to the component then the meta tag is not rendered.

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-02-12 17:51
Yes, the implementation as you described is ok but I've tested it and the app throws an error when those SSO tags are left empty in the app.

**Comment by Simply007** [comment] 2019-02-14 12:20
I will take a look at the #125 pull request and let you know!

**Comment by Simply007** [comment] 2019-02-14 13:05
I have gone through the pull request and everything works fine.

According to the metadata (i.e. ogImage) I would recommend using the lodash for the value check:
```
import _ from 'lodash';
...
      {!_.has(props, 'ogImage.value[0].url') ? null : ( // {!props.ogImage ? null : (
        <meta property="og:image" content={props.ogImage.value[0].url} />
      )}
```

But I am completely fine to accept the pull request without it. 
So it depends on you whether you want to implement it!

Great jop @Karl-EdwardFPJeanMehu, thanks!

**Comment by Karl-EdwardFPJeanMehu** [comment] 2019-02-16 09:05
Thanks @Simply007 !

**Closed** 2019-02-18 08:05 UTC
Labels: bug, groomed, hacktoberfest, help wanted, refactoring, up-for-grabs
